# Generated by Django 4.1.5 on 2023-08-14 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams', models.IntegerField()),
                ('roster_spots', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('team_image', models.ImageField(null=True, upload_to='')),
                ('draft_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.draft')),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.ImageField(null=True, upload_to='')),
                ('football_team', models.TextField(max_length=50, null=True)),
                ('pick_round', models.IntegerField()),
                ('position', models.CharField(max_length=10)),
                ('draft_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.draft')),
            ],
        ),
    ]
