# Generated by Django 4.2.4 on 2023-08-15 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pick_pick_number_alter_pick_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.draft')),
            ],
        ),
    ]
