# Generated by Django 4.1.5 on 2023-08-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pick_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='icon',
            field=models.CharField(default='https://a.espncdn.com/combiner/i?img=/games/lm-static/ffl/images/nomug.png&w=96&h=70&cb=1', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_image',
            field=models.CharField(default='https://g.espncdn.com/lm-static/ffl/images/default_logos/20.svg', max_length=400),
        ),
    ]
