# Generated by Django 4.2.4 on 2023-08-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='year',
            field=models.PositiveIntegerField(default=2023, null=True),
        ),
        migrations.AlterField(
            model_name='draft',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
