# Generated by Django 4.2.4 on 2023-08-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_draft_year_alter_draft_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='icon',
            field=models.CharField(default='https://a.espncdn.com/combiner/i?img=/games/lm-static/ffl/images/nomug.png&w=96&h=70&cb=1'),
        ),
    ]
