# Generated by Django 4.2.4 on 2023-08-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_pick_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pick',
            name='icon',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_image',
            field=models.ImageField(default='N/A', upload_to=''),
        ),
    ]
