# Generated by Django 4.2.4 on 2023-08-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_team_team_number_alter_pick_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_number',
        ),
        migrations.AlterField(
            model_name='team',
            name='team_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
