# Generated by Django 4.2.4 on 2023-08-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_team_team_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_image',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
    ]
