# Generated by Django 4.2.4 on 2023-08-15 23:43

import auth_token.utils.token_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_type', models.CharField(choices=[('frontend', 'Frontend'), ('extension', 'Chrome Extension')], max_length=10)),
                ('token', models.CharField(default=auth_token.utils.token_utils.generate_token, max_length=255)),
            ],
        ),
    ]
