# Generated by Django 4.2.4 on 2023-08-14 23:12

import auth_token.utils.token_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_token', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default=auth_token.utils.token_utils.generate_token, max_length=255),
        ),
    ]
